const fields = {
  types: {
    key: 'Types',
    label: 'Types',
    type: 'select',
    domainValues: ['Client', 'Partner', 'Tenant'],
    row: 1,
    column: 1,
    required: true,
  },
  name: {
    key: 'Name',
    label: 'Name',
    type: 'input',
    row: 1,
    column: 2,
    required: true,
  },
  website: {
    key: 'Website',
    label: 'Website',
    type: 'input',
    row: 1,
    column: 3,
    required: true,
  },
  street: {
    key: 'Street',
    label: 'Street',
    type: 'input',
    row: 2,
    column: 1,
    required: true,
  },
  zipcode: {
    key: 'Zipcode',
    label: 'Zip Code',
    type: 'input',
    row: 2,
    column: 2,
    required: true,
  },
  city: {
    key: 'City',
    label: 'City',
    type: 'select',
    row: 3,
    column: 1,
    required: true,
  },
  country: {
    key: 'Country',
    label: 'Country',
    type: 'select',
    row: 3,
    column: 2,
    required: true,
  },
  tags: {
    key: 'Tags',
    label: 'Tags',
    type: 'select',
    row: 4,
    column: 1,
    required: false,
  },
  notes: {
    key: 'Notes',
    label: 'Notes',
    type: 'textarea',
    row: 5,
    column: 1,
    required: false,
  },
};

export default fields;
